### ISSUE TITLE
Add signup endpoint

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_api#139]
We have `session_login` and `session_logout` endpoints, which helps with quickly prototyping an app.

It would be great to have a `session_signup` endpoint too.

It would look very similar to the login form, except with username / email / password / confirm password fields:

<img width="575" alt="Screenshot 2022-04-19 at 19 11 03" src="https://user-images.githubusercontent.com/350976/164068599-7df4bfbc-b39b-4f95-842b-b48738ec9375.png">

**Comment by sinisaos** [comment]
@dantownsend I was thinking the same thing yesterday and it would be useful. Can I try implement this? My only question is how deep should we go with email and password validation without an external library. Is the html email field enough and is the 6-character password long enough? Or should we go deeper with regular expression?

**Comment by dantownsend** [comment]
@sinisaos Thanks, it would great if you could take a look. Just a simple regex should be OK for email validation. Even if the first version is very simple, it's still useful. I think we can add hooks at some point, so users can add additional logic for password and email validation.

**Comment by sinisaos** [comment]
@dantownsend I will make PR during the day that you can see code changes. We will drop a little bit in coverage because multiple lines like [this](https://github.com/piccolo-orm/piccolo_api/blob/6f656a9048d482419efac329be888bdf45f8c136/piccolo_api/session_auth/endpoints.py#L182 ) one used to render errors in the HTML template. I think it's not a big deal.

**Comment by dantownsend** [comment]
Implemented in https://github.com/piccolo-orm/piccolo_api/pull/141
