### ISSUE TITLE
Starlite support

### ISSUE THREAD

**Issue by mastercoms** [piccolo-orm/piccolo_api#214]
[Starlite](https://github.com/starlite-api/starlite) is an up and coming [alternative](https://github.com/starlite-api/starlite#the-name-starlite-and-relation-to-starlette) to Starlette/FastAPI. It would be great to have the option to use the Starlite package instead, though I understand this would be an extensive and intrusive change.

**Comment by sinisaos** [comment]
@mastercoms I think that would be too much work because PiccoloCrud and FastAPIWrapper are based on Starlette and FastAPI. Also Piccolo Admin is based on FastAPI. If you want to use Starlite, there is a Starlite Piccolo asgi template. I made some [starter template](https://github.com/sinisaos/starlite-piccolo) with Starlite and Piccolo to see how it fits together and had no problems integrating Piccolo with Starlite.

**Comment by sinisaos** [comment]
> We did some work with the Starlite team to make sure `piccolo_admin` can be mounted within `starlite`, so hopefully that's also the case for things like `PiccoloCRUD`. Here's the issue about it: [piccolo-orm/piccolo_admin#211](https://github.com/piccolo-orm/piccolo_admin/issues/211)

@dantownsend You're right. We can mount `PiccoloCRUD` just like `Piccolo Admin` and every `PiccoloCRUD` endpoint works. 
```python
from piccolo_admin.endpoints import create_admin
from piccolo_api.crud.endpoints import PiccoloCRUD

# mounting Piccolo Admin
@asgi("/admin/", is_mount=True)
async def admin(scope: "Scope", receive: "Receive", send: "Send") -> None:
    await create_admin(tables=APP_CONFIG.table_classes)(scope, receive, send)


# mounting PiccoloCRUD
@asgi("/tasks/", is_mount=True)
async def crud(scope: "Scope", receive: "Receive", send: "Send") -> None:
    await PiccoloCRUD(table=Task)(scope, receive, send)

app = Starlite(
    route_handlers=[admin, crud],
    ...
)
```
When I tried that, I noticed that the Starlite asgi template doesn't work as it should, because now Starlite has different imports. If you want I can update the Starlite Piccolo asgi template to work as expected.

**Comment by dantownsend** [comment]
@sinisaos Thanks for checking that.

Did Starlite recently change their imports? We run a test in Piccolo to make sure the ASGI templates work, so maybe it's a recent thing?

**Comment by sinisaos** [comment]
@dantownsend Yes, 5 days ago. Before everything was  `from starlite import StaticFilesConfig` and now is
`from starlite.config.static_files import StaticFilesConfig` etc.

**Comment by dantownsend** [comment]
@sinisaos OK, cool - if you could change the template that would be great.

**Comment by mastercoms** [comment]
Awesome, thanks for the investigation and help!

**Comment by sinisaos** [comment]
@dantownsend No problem, I'll do it now.

**Comment by mastercoms** [comment]
So is there any interest in adding a StarliteWrapper then? Maybe I could help out here.

**Comment by dantownsend** [comment]
@mastercoms I haven't given it much thought, but it should be doable.

If you want to have a go, that would be great. I imagine the implementation will be very similar to `FastAPIWrapper`.

My main concerns are:

* The Starlite API still seems to be evolving - hopefully we can build upon it without any major breaking changes in the future.
* We've had problems in the past with supporting Starlite and FastAPI, because they sometimes depend on conflicting versions of Starlette. So if possible we should keep `starlite` as an optional dependency.

Having said that, I think it's OK.

**Comment by sinisaos** [comment]
@mastercoms I agree with @dantownsend,  but I think it's a big task because `FastAPIWrapper` depends on `PiccoloCRUD` which is based on `Starlette`, and `Starlette` has been removed as a dependency on `Starlite` since version `1.39.0` (in theory you first need to make Starlite-based` PiccoloCRUD`). If you still want to make `StarliteWrapper` (which is based on `Starlette` `PiccoloCRUD`), I think (not sure) it will probably be quite different than `FastAPIWrapper` because `Starlite` [routing has different implementation](https://starliteproject.dev/lib/usage/routing.html) than `FastAPI`. I think that would be a big task, but feel free to try that if you want.

**Comment by dantownsend** [comment]
@sinisaos Interesting - I didn't realise Starlite no longer had Starlette as a dependency.

Since `FastAPI` and `Starlette` share the same request object, it makes `FastAPIWrapper` quite simple. But to make a `StarliteWrapper` work, it would have to convert a Starlite request object into a Starlette request object - not sure how straight forward that is.

**Comment by sinisaos** [comment]
@dantownsend Yes, `Starlite` does not use `Starlette` [as dependencies any more](https://github.com/starlite-api/starlite#the-name-starlite-and-relation-to-starlette) and that's one of the reasons why I think making a `StarliteWrapper` would be a big task (as well as the other reasons I wrote before). `FastAPIWrapper` and `PiccoloCRUD` are very convenient methods to get a lot with a little code, but in the case of `Starlite` I think it's much simpler to write your own queries. [Here is an example](https://github.com/sinisaos/starlite-piccolo/tree/main/backend) I made to see how `Piccolo` and `Starlite` work together and I had no problems. I didn't even use [PiccoloORMPlugin](https://starliteproject.dev/lib/usage/plugins/piccolo-orm.html) (which is basically a wrapper around `create_pydantic_model` so you can use tables directly as request and response model in endpoints) but directly used `create_pydantic_model`.

**Comment by dantownsend** [comment]
@sinisaos Thanks for the info - that's useful to know. I'll have to play around with Starlite some more.

**Comment by mastercoms** [comment]
Yeah, that's actually what prompted me to make this, I saw that Starlette dependency and imports in the source, so I didn't know if it would be compatible.

**Comment by mastercoms** [comment]
I'm using FastAPI for now, so I'm not looking into any Starlite work atm

**Comment by sinisaos** [comment]
@mastercoms I think you should close this issue as this is unlikely to be implemented as we discussed before. Thanks.
