### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'excluded_paths'

### ISSUE THREAD

**Issue by hoosnick** [piccolo-orm/piccolo_api#232]
> `TypeError: __init__() got an unexpected keyword argument 'excluded_paths'`

```python
app = FastAPI(
    dependencies=[Depends(APIKeyHeader(name="Authorization"))],
    middleware=[
        Middleware(
            AuthenticationMiddleware,
            backend=TokenAuthBackend(
                SecretTokenAuthProvider(tokens=["abc123"]),
                excluded_paths=["/docs", "/openapi.json"],
            ),
        )
    ],
    ...
```
The [example](https://piccolo-api.readthedocs.io/en/latest/token_auth/middleware.html#excluded-paths) shown in the docs doesn't work. I have `Piccolo-API` version `0.54.0` installed.

**Comment by sinisaos** [comment]
@hoosnick Yes, you're right. It doesn't work, but not because the example isn't valid, but because somehow (I don't know how) the code from the master is not in the realesed package. When I run `pip install piccolo-api` version `0.54.0` token auth `middleware.py` has no new code from [master at all](https://github.com/piccolo-orm/piccolo_api/blob/master/piccolo_api/token_auth/middleware.py).
@dantownsend `Piccolo-API` version `0.54.0` has no code from master.  Weird.

**Comment by dantownsend** [comment]
Sorry about that - will do a release

**Comment by sinisaos** [comment]
@dantownsend I'm sorry. Now I see that you haven't released new changes.

**Comment by dantownsend** [comment]
Yeah, I should've released that sooner, as the docs auto update as soon as something hits the main branch.

`piccolo-api 0.55.0` was just released which contains the changes.

**Comment by hoosnick** [comment]
Got it, I installed the package from github for now:
`pip install git+https://github.com/piccolo-orm/piccolo_api.git#egg=piccolo-api`
