### ISSUE TITLE
Updating middleware syntax

### ISSUE THREAD

**Issue by jrycw** [piccolo-orm/piccolo_api#276]
I've been exploring the ASGI protocol and noticed that some middlewares are transitioning from the `async def dispatch(self, request, call_next)` style to `async def __call__(self, scope, receive, send)`. I've observed that certain middlewares in `piccolo-api` have already adopted this approach. I'm considering whether it would be beneficial to gradually update other middlewares as well. As a personal exercise, I chose to work on the [rate-limiting middleware](https://github.com/jrycw/piccolo-api-middlewares/blob/master/src/rate_limiting.py), and it seems to be passing the tests. @dantownsend , I'm curious to know if you're in favor of this transition.

**Comment by dantownsend** [comment]
You're right - the middleware in Piccolo API is a mix of different styles.

The way I remember it, is `async def __call__(self, scope, receive, send)` is a 'pure' ASGI middleware. If you look at the ASGI spec itself, this is how it expects middleware to behave.

The middleware which uses `async def dispatch(self, request, call_next)` is based off Starlette's `BaseHTTPMiddleware`, which adds a level of abstraction, so you deal with a request object, which arguably is simpler.

I'm not sure which is generally preferred nowadays - I imagine that both will work for the foreseeable future. Which one do you think is best?

**Comment by jrycw** [comment]
Both options seem excellent. The determining factor may depend on package dependencies. For example, I've heard that `litestar` originally relied on `starlette`, but that may no longer be the case.

**Comment by dantownsend** [comment]
Yeah, litestar no longer has starlette as a dependency. We sometimes found it problematic in the past, because litestar and fastapi would require conflicting versions of starlette.

`piccolo_api` has fastapi as a dependency, which could possibly be changed to an optional dependency.

I was thinking about the different styles of middleware that Piccolo API uses recently, but can't remember what I decided.

@sinisaos Do you have any thoughts on the different styles of middleware?

**Comment by sinisaos** [comment]
> Yeah, litestar no longer has starlette as a dependency. We sometimes found it problematic in the past, because litestar and fastapi would require conflicting versions of starlette.
> 

`Starlette` is not `Litestar` dependency for a long time (I think from version 1.50 or something like that).

> `piccolo_api` has fastapi as a dependency, which could possibly be changed to an optional dependency.

I think we will have a hard time putting `FastAPI` as an optional dependency without major code interventions, because we need `FastAPI` for `FastAPIWrapper` which is the base for Piccolo Admin. I think we should stick with `FastAPI` as the most popular and used ASGI framework. Other options (but not nearly as popular) are `BlackSheep` (which has been slower to maintaince lately) or `Litestar` (I've even made some contributions, but I'm kind of having a hard time reading Litestar's source code). I think `FastAPI` is still the best option for something like `FastAPIWrapper`.

Both variants are equally good, but I find the middleware based on Starlette `BaseHTTPMiddleware` a bit cleaner and clearer (atleast for me).

**Comment by jrycw** [comment]
I'll proceed with closing this issue since it seems there's no more input. Thank you, @dantownsend and @sinisaos , for your participation!

**Comment by dantownsend** [comment]
@jrycw Thanks. Let's leave the middleware as it is for now then, and we can always revisit it in the future 👍
